### ISSUE TITLE
Apply configurations

### ISSUE THREAD

**Issue by bopinto** [germanklf/maven-m2e-codestyle#7]
I'm using the plugin to import the formatter settings (`org.eclipse.jdt.ui.prefs`).
The problem is that, when I import the project, the configuration file is downloaded, the formatter settings are well configured, but the Java files are not well formatted.
The workaround is to go to `Project Properties > Java code style > Formatter > click 'Apply'`. Then, the files appear well formatted.

Any thoughts on how to solve this?

PS: my `org.eclipse.jdt.ui.prefs` file:

```
eclipse.preferences.version=1
formatter_profile=org.eclipse.jdt.ui.default.eclipse_profile
formatter_settings_version=12
```

**Comment by germanklf** [comment]
I don't have a clue... maybe is a version issue, which Eclipse version are you using?

BTW: I'm no longer supporting this tool, if you find the problem, you can patch it and I'll merge it.

**Comment by bopinto** [comment]
I'm using plugin version 1.0.3 with Eclipse Kepler.

**Comment by bopinto** [comment]
Fixed the issue. I was also saving the `jdt.core` preferences in the repository, but they didn't correspond to the Eclipse profile.
